facturacion/urls.py
from django.contrib import admin
from django.urls import path,include




urlpatterns = [
    path('', include(('front.urls', 'front'), namespace= 'front')),
    path('catalogos/', include(('catalogos.urls','catalogos'), namespace='catalogos')),
    path('admin/', admin.site.urls),
]

front/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from front.views import Home, HomeSinPrivilegios




urlpatterns = [
    path('', Home.as_view(),name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='front/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='front/login.html'),name='logout'),
    path('sin_privilegios/',HomeSinPrivilegios.as_view(), name='sin_privilegios'),

]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
        {% block head_title %}
        Curso Django Práctico - Creando APP Facturación
        {% endblock head_title %}
    </title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'base/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'base/css/metisMenu.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'base/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'base/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Datatable-->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/r-2.2.2/datatables.min.css"/>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'front:home' %}">Curso Django</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> {{ user.username }} <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="{% url 'front:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="#"><i class="fa fa-cogs fa-fw"></i> Catálogos <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'catalogos:categoria_list' %}">Categorias</a>
                                    <a href="{% url 'catalogos:subcategoria_list' %}">Sub Categorias</a>
                                    <a href="{% url 'catalogos:producto_list' %}">Productos</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-inbox fa-fw"></i> Salidas<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li> <a href="{% url 'salidas:factura_list' %}">Facturación</a> </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <small class="text-danger">
                    {% if form.errors %}
                    {% for field in form %}
                    {% if field.errors %}
                    {% for error in field.errors %}
                    {{ error|escape }}
                    {% endfor %}
                    {% endif %}
                    {% endfor %}
                    {% if form.non_field_errors%}
                    {% for error in form.non_field_errors %}
                    {{ error|escape }}
                    {% endfor %}
                    {% endif %}
                    {% endif %}
                </small>
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            <small class="text-danger text-center">
                                {% if messages %}
                                {% for message in messages %}
                                {{ message|safe }}<br>
                                {% endfor %}
                                {% endif %}
                            </small>
                        </h1>
                        {% block contenido %}Blank{% endblock contenido %}
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{% static 'base/js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'base/js/metisMenu.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'base/js/sb-admin-2.js' %}"></script>

    <!-- Datatable-->
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/r-2.2.2/datatables.min.js"></script>

    <script>
        $(document).ready( function () {
            $('#dataTables-example').DataTable(
                {
                    responsive: true
                }
            );
        } );
    </script>
</body>

</html>